name: Assign team on label

on:
  issues:
    types: [labeled] # Trigger the workflow when an issue is labeled

jobs:
  assign-team:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Necessary to modify issue assignees
      pull-requests: write # Can be useful if the action supports PRs too
    steps:
      - name: "Assign team based on label"
        uses: toshimaru/label-based-reviewer-auto-assign-action@v1 # Use the actual action version
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          config-path: ".github/label-actions.yml"
